# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
nombre = "Juan Esteban Amariles"
edad = 35
print(f"Hola, me llamo {nombre} y tengo {edad} años.")


Hola, me llamo Juan Esteban Amariles y tengo 35 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [2]:
numeros = [10, 25, 3, 47, 8, 15]

print(f"El primer número es: {numeros[0]}, y el último número es: {numeros[-1]}")
print(f"los 3 primeros números son: {numeros[:3]}")
numeros.append(99)
print(f"La lista actualizada es: {numeros}")


El primer número es: 10, y el último número es: 15
los 3 primeros números son: [10, 25, 3]
La lista actualizada es: [10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [3]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

if estudiante["promedio"] >= 6:
    print("Aprobado")
else:    
    print("Reprobado") 



Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [6]:
def calcular_area(base, altura):
    area = (base * altura) / 2
    return area

base = 5
altura = 8
area_triangulo = calcular_area(base, altura)
print(f"El área del triángulo con base {base} y altura {altura} es: {area_triangulo}")


El área del triángulo con base 5 y altura 8 es: 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [7]:

cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [8]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [9]:

arreglo1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Arreglo 1:")
print(arreglo1)
print("Shape:", arreglo1.shape)
print("Dtype:", arreglo1.dtype)

matriz_ceros = np.zeros((3, 4))
print("\nMatriz de ceros:")
print(matriz_ceros)
print("Shape:", matriz_ceros.shape)
print("Dtype:", matriz_ceros.dtype)

arreglo2 = np.linspace(0, 1, 6)
print("\nArreglo con 6 valores igualmente espaciados entre 0 y 1:")
print(arreglo2)
print("Shape:", arreglo2.shape)
print("Dtype:", arreglo2.dtype)



Arreglo 1:
[1.5 2.5 3.5 4.5]
Shape: (4,)
Dtype: float64

Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64

Arreglo con 6 valores igualmente espaciados entre 0 y 1:
[0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [10]:
a = np.arange(1, 13)

matriz_3x4 = a.reshape(3, 4)
print("Matriz 3x4:")
print(matriz_3x4)
maximo = matriz_3x4.max()
minimo = matriz_3x4.min()
indice_maximo = matriz_3x4.argmax()
print(f"Valor máximo: {maximo}")
print(f"Valor mínimo: {minimo}")
print(f"Índice del valor máximo: {indice_maximo}")



Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Valor máximo: 12
Valor mínimo: 1
Índice del valor máximo: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [13]:

arreglo_a = np.random.randint(1, 21, size=5)
arreglo_b = np.random.randint(1, 21, size=5)
print("Arreglo A:", arreglo_a)
print("Arreglo B:", arreglo_b)
suma = arreglo_a + arreglo_b
resta = arreglo_a - arreglo_b
producto = arreglo_a * arreglo_b
print("Suma:", suma)
print("Resta:", resta)
print("Producto:", producto)



Arreglo A: [19  4 12  1 13]
Arreglo B: [17 13 18 17  9]
Suma: [36 17 30 18 22]
Resta: [  2  -9  -6 -16   4]
Producto: [323  52 216  17 117]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [14]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

notas_mayores_6 = notas[notas >= 6]
print("Notas mayores o iguales a 6:", notas_mayores_6)



Notas mayores o iguales a 6: [ 8.5  6.   9.2  7.8 10. ]
